name: QA Deploy

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trigger Dokploy deploy
        run: |
          curl -X POST ${{ secrets.DOKPLOY_WEBHOOK_URL }} \
            -H "Content-Type: application/json"