name: QA Deploy

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trigger Dokploy deploy
        run: |
          curl -X POST http://localhost:3000/api/deploy/compose/9IwqljSqr4o-NsFxrYwhH \
            -H "Content-Type: application/json"